export function throwError() {
    throw Error("An exception")
}